modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/OpenMods/OpenModsLib"

[[mods]]
modId="openmods"
version="${file.jarVersion}"
displayName="OpenModsLib"
updateJSONURL="http://openmods.info/versions/openmodslib.json"
displayURL="https://openmods.info/" #optional
credits="Original authors: Mikee, NeverCast, Lyqyd"
authors="boq"
description="Boring stuff for all that silly Open* mods"
[[dependencies.openmods]]
    modId="forge"
    mandatory=true
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.openmods]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"